version: '3.4'
services:
  frontend_service:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVICE_URL=http://127.0.0.1:8000
    depends_on:
      - web_service

  web_service:
    build: ./backend
    command: uvicorn src.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./.data:/data
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - AIVEN_SERVICE_URL=https://api.aiven.io/v1
      - CLOUD_PLATFORMS_HYDRATE_PERIOD_SEC=1800
